jobs:
  deploy:
    name: Upload to AWS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Zip folder
      run: zip -r function.zip ./lambda-functions

    - name: Copy files to AWS
      run: |
        aws lambda update-function-code --function-name star-wars-morals --zip-file fileb://function.zip